Embedded Command Line: cmd.c File Reference
cmd.c File Reference
#include "stdlib.h"
#include "cmd.h"
#include "string.h"
Functions
void cmd_print_comands_brief (cmd_line_desc_ptr_t cmd_line_desc, const cmd_desc_t **cmd_list, uint8_t indent_level)
void cmd_print_command_description (cmd_line_desc_ptr_t cmd_line_desc, const cmd_desc_t **cmd_list, const char *cmd_name)
int cmd_do_help (int argc, char **argv, cmd_line_desc_ptr_t cmd_line_desc)
int cmd_do_version (int argc, char **argv, cmd_line_desc_ptr_t cmd_line_desc)
Variables
__weak const char * cmd_line_fw_version = "unknown"
cmd_desc_t cmd_desc_help
cmd_desc_t cmd_desc_version
const cmd_desc_t * basic_cmd_list []
Function Documentation
int cmd_do_help (int argc, char ** argv, cmd_line_desc_ptr_t cmd_line_desc)
Definition at line 44 of file cmd.c.
References cmd_line_get_root_list(), CMD_LINE_SUCCESS, cmd_print_comands_brief(), and cmd_print_command_description().
int cmd_do_version (int argc, char ** argv, cmd_line_desc_ptr_t cmd_line_desc)
Definition at line 60 of file cmd.c.
References cmd_line_fw_version, cmd_line_printf_tk(), and CMD_LINE_SUCCESS.
void cmd_print_comands_brief (cmd_line_desc_ptr_t cmd_line_desc, const cmd_desc_t ** cmd_list, uint8_t indent_level)
Definition at line 14 of file cmd.c.
References CMD_LINE_MAX_INDENT, cmd_line_printf_tk(), and CMD_LINE_SUBLIST_MARK.
Referenced by cmd_do_help().
void cmd_print_command_description (cmd_line_desc_ptr_t cmd_line_desc, const cmd_desc_t ** cmd_list, const char * cmd_name)
Definition at line 37 of file cmd.c.
References cmd_line_find_command_by_name(), cmd_line_printf_tk(), and cmd_desc_st::description.
Referenced by cmd_do_help().
Variable Documentation
cmd_desc_t cmd_desc_help
Initial value:
=
    {
        .name = "help",
        .one_line = "Prints help for built in commands.",
        .description = "help [command]\r\n"
            "Prints a complete list of commands with short description or a\r\n"
            "complete description for one command, if the name is given as parameter.\r\n"
            "\r\n"
            "Example:\r\n"
            "\t--> help help\r\n"
            "\thelp [command]\r\n"
            "\t...\r\n",
        .cmd_fcn = &cmd_do_help
    }
Definition at line 65 of file cmd.c.
cmd_desc_t cmd_desc_version
Initial value:
=
    {
        .name = "version",
        .one_line = "Prints The version of the firmware.",
        .description = "version\r\n"
            "Prints The version of the firmware.\r\n"
            "\r\n"
            "Example:\r\n"
            "\t--> version\r\n"
            "\tFirmware version: 1.0a\r\n",
        .cmd_fcn = &cmd_do_version
    }
Definition at line 80 of file cmd.c.