Embedded Command Line: cmdline.c File Reference
cmdline.c File Reference
#include "cmdline.h"
#include <stdarg.h>
#include <string.h>
#include <ctype.h>
Data Structures
struct cmd_line_desc
struct cmd_lines_pool_st
Functions
int rb_push (cmd_line_desc_ptr_t cmd_line_desc, char c)
int rb_pop (cmd_line_desc_ptr_t cmd_line_desc, char *c)
int cmd_line_printf_parse (cmd_line_desc_ptr_t cmd_line_desc, const char *format,...)
const cmd_desc_t * cmd_line_find_command_by_name (const cmd_desc_t **cmd_line_root_list, const char *cmd_name, uint8_t indent_level)
cmd_line_desc_ptr_t cmd_line_init (const cmd_line_init_t *init)
int cmd_line_process (cmd_line_desc_ptr_t cmd_line_desc)
const char * cmd_line_get_prompt (cmd_line_desc_ptr_t cmd_line_desc)
int cmd_line_printf (cmd_line_desc_ptr_t cmd_line_desc, const char *format,...)
int cmd_line_printf_tk (cmd_line_desc_ptr_t cmd_line_desc, const char *format,...)
char cmd_line_getchar (cmd_line_desc_ptr_t cmd_line_desc)
char cmd_line_getchar_tk (cmd_line_desc_ptr_t cmd_line_desc)
const cmd_desc_t ** cmd_line_get_root_list (cmd_line_desc_ptr_t cmd_line_desc)
void cmd_line_uart_rx_cb (cmd_line_desc_ptr_t cmd_line_desc, char c)
Function Documentation
int cmd_line_printf_parse (cmd_line_desc_ptr_t cmd_line_desc, const char * format, ...)
Definition at line 89 of file cmdline.c.
References CMD_LINE_PRINTF_ERR_LENGTH, CMD_LINE_PRINTF_ERR_PARSE, cmd_line_desc::tx_buf, and cmd_line_desc::tx_buf_len.
Referenced by cmd_line_printf(), and cmd_line_printf_tk().
int rb_pop (cmd_line_desc_ptr_t cmd_line_desc, char * c)
Definition at line 74 of file cmdline.c.
References cmd_line_desc::rx_buf, cmd_line_desc::rx_buf_head, cmd_line_desc::rx_buf_max_len, and cmd_line_desc::rx_buf_tail.
Referenced by cmd_line_getchar(), and cmd_line_getchar_tk().
int rb_push (cmd_line_desc_ptr_t cmd_line_desc, char c)
Definition at line 58 of file cmdline.c.
References cmd_line_desc::rx_buf, cmd_line_desc::rx_buf_head, cmd_line_desc::rx_buf_max_len, and cmd_line_desc::rx_buf_tail.
Referenced by cmd_line_uart_rx_cb().