Embedded Command Line: Interface
Interface
Modules
Return values
Wrappers
Input Output
Data Structures
struct cmd_line_init_st
Typedefs
typedef struct cmd_line_desc * cmd_line_desc_ptr_t
typedef struct cmd_line_init_st cmd_line_init_t
Functions
cmd_line_desc_ptr_t cmd_line_init (const cmd_line_init_t *init)
int cmd_line_process (cmd_line_desc_ptr_t cmd_line_desc)
const char * cmd_line_get_prompt (cmd_line_desc_ptr_t cmd_line_desc)
const cmd_desc_t ** cmd_line_get_root_list (cmd_line_desc_ptr_t cmd_line_desc)
void cmd_line_uart_rx_cb (cmd_line_desc_ptr_t cmd_line_desc, char c)
const cmd_desc_t * cmd_line_find_command_by_name (const cmd_desc_t **cmd_line_root_list, const char *cmd_name, uint8_t indent_level)
Detailed Description
Typedef Documentation
typedef struct cmd_line_desc* cmd_line_desc_ptr_t
Command line instance descriptor.
Definition at line 67 of file cmdline.h.
typedef struct cmd_line_init_st cmd_line_init_t
Command line initialization data structure.
Declare and fill this structure in your program to pass it into cmd_line_init function.
Function Documentation
const cmd_desc_t* cmd_line_find_command_by_name (const cmd_desc_t ** cmd_line_root_list, const char * cmd_name, uint8_t indent_level)
Find command by its name.
Parameters
[in] cmd_line_root_list The root command list to search for command.
[in] cmd_name The name of the command to be looked for.
[in] indent_level Must be set to 0.
Returns
Pointer to the command descriptor, or NULL if no such command is defined.
Definition at line 104 of file cmdline.c.
References cmd_line_find_command_by_name(), CMD_LINE_MAX_INDENT, and CMD_LINE_SUBLIST_MARK.
Referenced by cmd_line_find_command_by_name(), cmd_line_process(), and cmd_print_command_description().
const char* cmd_line_get_prompt (cmd_line_desc_ptr_t cmd_line_desc)
Get the command line prompt string.
Parameters
[in] cmd_line_desc Command line instance descriptor.
Returns
Pointer to the command line instance prompt string.
Definition at line 218 of file cmdline.c.
References cmd_line_desc::prompt_text.
const cmd_desc_t** cmd_line_get_root_list (cmd_line_desc_ptr_t cmd_line_desc)
Get the root commands list.
Parameters
[in] cmd_line_desc Command line instance descriptor.
Returns
The pointer to the root commands list.
Definition at line 259 of file cmdline.c.
References cmd_line_desc::cmd_line_root_list.
Referenced by cmd_do_help().
cmd_line_desc_ptr_t cmd_line_init (const cmd_line_init_t * init)
Initialize the command line processor.
Call this function at the start of your program, before any other command line functions.
Parameters
[in] init Command line instance initialization data.
Returns
Command line instance descriptor.
Definition at line 137 of file cmdline.c.
References cmd_line_desc::arg_starts, cmd_line_init_st::args_starts, cmd_line_desc::cmd_line_root_list, CMD_LINES_MAX_CNT, cmd_lines_pool_st::cmd_lines_pool, cmd_line_init_st::cmd_root_lis, cmd_line_desc::echo_enabled, cmd_line_init_st::echo_enabled, cmd_line_desc::io_timeout_ms, cmd_line_init_st::io_timeout_ms, cmd_line_desc::line_buf, cmd_line_init_st::line_buf, cmd_line_desc::line_buf_current, cmd_line_desc::line_buf_len, cmd_line_init_st::line_buf_size, cmd_line_desc::max_args, cmd_line_init_st::max_args_cnt, cmd_line_init_st::prompt, cmd_line_desc::prompt_text, cmd_line_desc::rx_buf, cmd_line_init_st::rx_buf, cmd_line_desc::rx_buf_head, cmd_line_init_st::rx_buf_len, cmd_line_desc::rx_buf_max_len, cmd_line_desc::rx_buf_tail, cmd_line_desc::rx_err_cnt, cmd_line_init_st::rx_fn, cmd_line_desc::tx_buf, cmd_line_init_st::tx_buf, cmd_line_desc::tx_buf_len, cmd_line_init_st::tx_buf_len, cmd_line_desc::tx_err_cnt, cmd_line_init_st::tx_nb_fn, cmd_line_init_st::tx_tc_fn, cmd_line_desc::uart_rx_tc, cmd_line_desc::uart_tx_nb, and cmd_line_desc::uart_tx_tc.
int cmd_line_process (cmd_line_desc_ptr_t cmd_line_desc)
Command line processor main function.
Call this function periodically, e.g. in your main application loop, to process received commands.
Parameters
[in] cmd_line_desc Command line instance descriptor.
Returns
CMD_LINE_SUCCESS if a command was successfully executed, CMD_LINE_NO_CMD when the command line processor exited successfully without executing any command, or error code in case of failure.
Definition at line 171 of file cmdline.c.
References cmd_line_desc::arg_starts, cmd_desc_st::cmd_fcn, CMD_LINE_ERR_CMD_NOT_FOUND, cmd_line_find_command_by_name(), cmd_line_getchar(), CMD_LINE_NO_CMD, cmd_line_printf_tk(), cmd_line_desc::cmd_line_root_list, cmd_line_desc::echo_enabled, cmd_line_desc::line_buf, cmd_line_desc::line_buf_current, and cmd_line_desc::line_buf_len.
void cmd_line_uart_rx_cb (cmd_line_desc_ptr_t cmd_line_desc, char c)
Character received callback.
Call this when a character is received, e.g. in your UART RX ISR.
Parameters
[in] cmd_line_desc Command line instance descriptor.
[in] c Received character.
Definition at line 263 of file cmdline.c.
References rb_push(), and cmd_line_desc::rx_err_cnt.