Embedded Command Line: Input Output
Input Output
Interface
Functions
int cmd_line_printf (cmd_line_desc_ptr_t cmd_line_desc, const char *format,...)
int cmd_line_printf_tk (cmd_line_desc_ptr_t cmd_line_desc, const char *format,...)
char cmd_line_getchar (cmd_line_desc_ptr_t cmd_line_desc)
char cmd_line_getchar_tk (cmd_line_desc_ptr_t cmd_line_desc)
Detailed Description
Function Documentation
char cmd_line_getchar (cmd_line_desc_ptr_t cmd_line_desc)
Get char - nonblocking.
Returns immediately.
Parameters
[in] cmd_line_desc Command line instance descriptor.
Returns
Received character if any, EOF if the receive buffer is empty.
Definition at line 245 of file cmdline.c.
References rb_pop().
Referenced by cmd_line_process().
char cmd_line_getchar_tk (cmd_line_desc_ptr_t cmd_line_desc)
Get char - blocking.
Waits for character reception if the receive buffer is empty.
Parameters
[in] cmd_line_desc Command line instance descriptor.
Returns
Received character.
Definition at line 253 of file cmdline.c.
References rb_pop().
int cmd_line_printf (cmd_line_desc_ptr_t cmd_line_desc, const char * format, ...)
Print formatted string - nonblocking.
C stdio printf like function for printing formatted text to the command line output. Returns immediately. All characters that will not fit into transmit buffer (cmd_line_init_t::tx_buf) are discarded.
Parameters
[in] cmd_line_desc Command line instance descriptor.
[in] format printf like formatted string.
Returns
Number of printed characters, or negative error code value.
Definition at line 222 of file cmdline.c.
References CMD_LINE_ERR_GENERAL, cmd_line_printf_parse(), CMD_LINE_SUCCESS, cmd_line_desc::tx_buf, cmd_line_desc::tx_err_cnt, and cmd_line_desc::uart_tx_nb.
int cmd_line_printf_tk (cmd_line_desc_ptr_t cmd_line_desc, const char * format, ...)
Print formatted string - blocking.
C stdio printf like function for printing formatted text to the command line output. Blocks until all characters are printed.
Parameters
[in] cmd_line_desc Command line instance descriptor.
[in] format printf like formatted string.
Returns
Number of printed characters, or negative error code value.
Definition at line 234 of file cmdline.c.
References CMD_LINE_ERR_GENERAL, cmd_line_printf_parse(), CMD_LINE_SUCCESS, cmd_line_desc::tx_buf, cmd_line_desc::tx_err_cnt, and cmd_line_desc::uart_tx_tc.
Referenced by cmd_do_version(), cmd_line_process(), cmd_print_comands_brief(), and cmd_print_command_description().